backend:
  name: github
  repo: speechanddebate/tabroom-docs
  branch: main
  site_domain: sleepy-brahmagupta-750e3c.netlify.com

media_folder: "static/screenshots" # Media files will be stored in the repo under static/images/uploads
public_folder: "/screenshots/" # The src attribute for uploaded media will begin with /images/uploads

collections:
- name: docs
  label: "docs"
  folder: docs
  identifier_field: title
  extension: md
  widget: "list"
  create: true
  nested:
    depth: 100
    summary: "{{title}}"
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields:
    - { name: title, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
